// server/utils/disposableEmails.js
// ═══════════════════════════════════════════════════════════════
// LISTA DE DOMÍNIOS DE EMAIL DESCARTÁVEIS/TEMPORÁRIOS
// Usada no OTP controller + fraud protection middleware
// ═══════════════════════════════════════════════════════════════
// ✅ 31/03/2026: Lista expandida com 200+ domínios
// ✅ Inclui sharebot.net (usado no ataque de 31/03/2026)
// ═══════════════════════════════════════════════════════════════

export const disposableDomains = new Set([
  // ─── Domínios usados em ataques à Elite Surfing ───────────
  'sharebot.net',

  // ─── Serviços populares de email temporário ───────────────
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  'temp-mail.de',
  'tempail.com',
  'tempr.email',
  'tempinbox.com',
  'tempmailaddress.com',
  'tempmailo.com',
  'temporarymail.com',
  'temporary-mail.net',
  'throwaway.email',
  'throwaway.me',
  'throam.com',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.de',
  'guerrillamailblock.com',
  'grr.la',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'trashmail.com',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.io',
  'fakeinbox.com',
  'fakemail.net',
  'fakemail.fr',
  'sharklasers.com',
  'dispostable.com',
  'maildrop.cc',
  'maildrop.ml',
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minmail.com',
  'mohmal.com',
  'mohmal.im',
  'mohmal.in',

  // ─── Outros serviços conhecidos ────────────────────────────
  'mailnesia.com',
  'mailnull.com',
  'mailsac.com',
  'mailscrap.com',
  'mailslurp.com',
  'mailtemp.info',
  'mailtemp.net',
  'mailtothis.com',
  'mailzilla.com',
  'mintemail.com',
  'mytrashmail.com',
  'nomail.xl.cx',
  'nospam.ze.tc',
  'owlpic.com',
  'proxymail.eu',
  'rcpt.at',
  'safetymail.info',
  'spambox.us',
  'spamfree24.org',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamhole.com',
  'spaml.com',
  'spamspot.com',
  'tempinbox.co.uk',
  'thankyou2010.com',
  'thisisnotmyrealemail.com',
  'tradermail.info',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashdevil.com',
  'trashdevil.de',
  'trashymail.com',
  'trashymail.net',
  'twinmail.de',
  'uggsrock.com',
  'upliftnow.com',
  'venompen.com',
  'veryreallyme.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whyspam.me',
  'wilemail.com',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'wwwnew.eu',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xjoi.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yuurok.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zippymail.info',

  // ─── Descartáveis brasileiros / regionais ──────────────────
  'emailfake.ml',
  'emailfake.com',
  'crazymailing.com',
  'email-fake.com',
  'emailondeck.com',
  'fakemailgenerator.com',
  'generator.email',
  'getairmail.com',
  'getnada.com',
  'harakirimail.com',
  'inboxbear.com',
  'jetable.org',
  'mailcatch.com',
  'mailexpire.com',
  'mailforspam.com',
  'mailfree.ga',
  'mailhazard.com',
  'mailhazard.us',
  'mailhz.me',
  'mailimate.com',
  'mailmoat.com',
  'mailnator.com',
  'mailnull.com',
  'mailpick.biz',
  'mailproxsy.com',
  'mailquack.com',
  'mailrock.biz',
  'mailseal.de',
  'mailshell.com',
  'mailsiphon.com',
  'meltmail.com',
  'messagebeamer.de',
  'mierdamail.com',
  'ministry-of-silly-walks.de',
  'mt2015.com',
  'mytemp.email',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.ch',
  'nomail.xl.cx',
  'nomorespamemails.com',
  'nothingtoseehere.ca',
  'nurfuerspam.de',
  'nus.edu.sg',
  'oneoffemail.com',
  'onewaymail.com',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'ownsyou.de',
  'pjjkp.com',
  'plexolan.de',
  'pookmail.com',
  'privacy.net',
  'prtnx.com',
  'putthisinyouremail.com',
  'quickinbox.com',
  'rcpt.at',
  'reallymymail.com',
  'recode.me',
  'regbypass.com',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'scatmail.com',
  'schafmail.de',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'shiftmail.com',
  'shitmail.me',
  'shortmail.net',
  'sibmail.com',
  'skeefmail.com',
  'slaskpost.se',
  'slipry.net',
  'slopsbox.com',
  'smashmail.de',
  'soodonims.com',
  'spam4.me',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spamcero.com',
  'spamday.com',
  'spamex.com',
  'spamfighter.cf',
  'spamfighter.ga',
  'spamfighter.gq',
  'spamfighter.ml',
  'spamfighter.tk',
  'superstachel.de',
  'suremail.info',
  'teleworm.us',
  'tempalias.com',
  'tempe4mail.com',
  'tempemail.biz',
  'tempemail.co.za',
  'tempemail.com',
  'tempemail.net',
  'tempmailer.com',
  'tempmailer.de',
  'tempomail.fr',
  'tmpmail.net',
  'tmpmail.org',
  'trbvm.com',
  'trbvn.com',
]);

/**
 * Verifica se um domínio de email é descartável
 * @param {string} email - Email completo ou domínio
 * @returns {boolean} true se for descartável
 */
export const isDisposableEmail = email => {
  if (!email) return false;
  const domain = email.includes('@')
    ? email.split('@')[1].toLowerCase().trim()
    : email.toLowerCase().trim();
  return disposableDomains.has(domain);
};
